name: Mon CI

on:
  push:
    branches: [main, feature-readme, feature-test]

jobs:
  Construction:
    runs-on: ubuntu-latest

    steps:
      - name: RÃ©cupÃ©ration du code
        uses: actions/checkout@v4

      - name: VÃ©rification du contenu
        run: |
          echo "âœ… FÃ©licitations, Pipeline CI dÃ©clenchÃ© avec rÃ©ussite ğŸ‰"
          ls -l